name: Testing env variables
on:
  push:
    branches:
      - main
      
  pull_request:
    branches: [ "main" ]
env:
  DAY_OF_WEEK: Monday
  
      
      
jobs:
  env-job:
   runs-on: self-hosted
   env:
     Greeting: Hello
   steps:
     - uses: actions/checkout@v3
     - name: verify env variable
       run: echo "$Greeting $name .Today is $DAY_OF_WEEK"
       env:
         name: Madhuri
     - name: verify github environments
       run: echo '${{ toJSON(github) }}'
        
