name: Execute Script
on:
  push:
    branches:
      - main
jobs:
  example-job:
   runs-on: self-hosted
   steps:
     - name: Run build script
       shell: bash
       #id: mqm
       #continue-on-error: true
       run: ls
     - name: change the permissions  
       shell: bash
       run: chmod 764  createqlocal.sh
     - name : check the present working directory
       shell: bash
       run : pwd
