name: Execute Script
on:
  push:
    branches:
      - main
      
  pull_request:
    branches: [ "main" ]
  
      
      
jobs:
  example-job:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v3
     - name: Run build script
       shell: bash
       #id: mqm
       #continue-on-error: true
       run: ls
     - name: change the permissions  
       shell: bash
       run: chmod 764  createqlocal.sh
     - name : run the script
       id: mqm
       shell: bash
       run : sh createqlocal.sh QM2
